language: ruby
cache:
  directories:
    - /home/travis/.rvm/
    - ./vendor/bundle/
rvm:
 - 2.6.5
services:
  - postgresql
env:
  - PG_USER=postgres
script:
  - bundle exec rspec --format doc
install:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
